const { withDangerousMod, withMainApplication } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const AUDIO_METER_MODULE_KT = [
  `package com.snoresleep.monitor`,
  ``,
  `import android.Manifest`,
  `import android.content.pm.PackageManager`,
  `import android.media.AudioFormat`,
  `import android.media.AudioRecord`,
  `import android.media.MediaRecorder`,
  `import android.os.Process`,
  `import android.util.Log`,
  `import androidx.core.app.ActivityCompat`,
  `import com.facebook.react.bridge.*`,
  `import org.tensorflow.lite.Interpreter`,
  `import java.io.*`,
  `import java.nio.ByteBuffer`,
  `import java.nio.ByteOrder`,
  `import kotlin.math.*`,
  ``,
  `class AudioMeterModule(reactContext: ReactApplicationContext) : ReactContextBaseJavaModule(reactContext) {`,
  `    companion object {`,
  `        const val TAG = "AudioMeter"`,
  `        const val SAMPLE_RATE = 16000`,
  `        const val SAMPLES_PER_WINDOW = 16000`,
  `        const val FRAME_LENGTH_MS = 20`,
  `        const val FRAME_STRIDE_MS = 15.38`,
  `        const val FFT_LENGTH = 128`,
  `        const val NOISE_FLOOR_DB = -54.0`,
  `        const val EXPECTED_FEATURES = 4160`,
  `        const val INPUT_SCALE = 0.003921568859368563`,
  `        const val INPUT_ZERO_POINT = -128`,
  `        const val OUTPUT_SCALE = 0.00390625`,
  `        const val OUTPUT_ZERO_POINT = -128`,
  `    }`,
  ``,
  `    private var interpreter: Interpreter? = null`,
  `    private var audioRecord: AudioRecord? = null`,
  `    private var recordingThread: Thread? = null`,
  `    @Volatile private var isRecording = false`,
  ``,
  `    private var wavFilePath: String = ""`,
  `    private var wavOut: DataOutputStream? = null`,
  `    private var wavDataBytes: Int = 0`,
  ``,
  `    private val lock = Object()`,
  `    private var labels = listOf<String>()`,
  `    private var latestConfidences = emptyMap<String, Double>()`,
  `    private var latestTopClass = ""`,
  `    private var latestTopConfidence = 0.0`,
  `    private var latestIsSnoring = false`,
  `    private var latestAmplitudeDb = -100.0`,
  ``,
  `    override fun getName(): String = "AudioMeter"`,
  ``,
  `    @ReactMethod`,
  `    fun startRecording(promise: Promise) {`,
  `        try {`,
  `            if (ActivityCompat.checkSelfPermission(reactApplicationContext, Manifest.permission.RECORD_AUDIO) != PackageManager.PERMISSION_GRANTED) {`,
  `                throw SecurityException("RECORD_AUDIO permission not granted")`,
  `            }`,
  ``,
  `            // Load label names from assets. The label file lets the same native code work with`,
  `            // any TFLite model by reporting class names and confidences generically.`,
  `            labels = loadLabels()`,
  `            if (labels.isEmpty()) {`,
  `                labels = listOf("noise", "snoring")`,
  `            }`,
  ``,
  `            // Copy TFLite model from assets to a regular file for the interpreter`,
  `            val modelFile = File(reactApplicationContext.filesDir, "snore_detection.tflite")`,
  `            if (!modelFile.exists()) {`,
  `                reactApplicationContext.assets.open("snore_detection.tflite").use { input ->`,
  `                    FileOutputStream(modelFile).use { output ->`,
  `                        input.copyTo(output)`,
  `                    }`,
  `                }`,
  `            }`,
  `            val opts = Interpreter.Options().setNumThreads(2)`,
  `            interpreter = Interpreter(modelFile, opts)`,
  ``,
  `            // Prepare WAV recording`,
  `            val recordingsDir = File(reactApplicationContext.cacheDir, "recordings").apply { mkdirs() }`,
  `            val file = File(recordingsDir, "recording_\${System.currentTimeMillis()}.wav")`,
  `            wavFilePath = file.absolutePath`,
  `            wavOut = DataOutputStream(BufferedOutputStream(FileOutputStream(file)))`,
  `            writeWavHeader(wavOut!!, 0)`,
  `            wavDataBytes = 0`,
  ``,
  `            // Initialize AudioRecord (16 kHz, mono, 16-bit PCM)`,
  `            val minBufferSize = AudioRecord.getMinBufferSize(SAMPLE_RATE, AudioFormat.CHANNEL_IN_MONO, AudioFormat.ENCODING_PCM_16BIT)`,
  `            val bufferSize = max(minBufferSize, SAMPLE_RATE * 2)`,
  `            audioRecord = AudioRecord(MediaRecorder.AudioSource.MIC, SAMPLE_RATE, AudioFormat.CHANNEL_IN_MONO, AudioFormat.ENCODING_PCM_16BIT, bufferSize)`,
  `            if (audioRecord?.state != AudioRecord.STATE_INITIALIZED) {`,
  `                throw IllegalStateException("AudioRecord failed to initialize")`,
  `            }`,
  ``,
  `            audioRecord?.startRecording()`,
  `            isRecording = true`,
  `            startAudioProcessing()`,
  ``,
  `            promise.resolve("file://\$wavFilePath")`,
  `        } catch (e: Exception) {`,
  `            Log.e(TAG, "startRecording failed", e)`,
  `            releaseResources()`,
  `            promise.reject("START_ERROR", e.message ?: "Unknown error")`,
  `        }`,
  `    }`,
  ``,
  `    @ReactMethod`,
  `    fun stopRecording(promise: Promise) {`,
  `        isRecording = false`,
  `        try {`,
  `            recordingThread?.join(1500)`,
  `        } catch (_: InterruptedException) {}`,
  `        recordingThread = null`,
  `        releaseResources()`,
  `        promise.resolve("file://\$wavFilePath")`,
  `    }`,
  ``,
  `    @ReactMethod`,
  `    fun getLatestResult(promise: Promise) {`,
  `        val map = Arguments.createMap()`,
  `        val confidencesMap = Arguments.createMap()`,
  `        synchronized(lock) {`,
  `            for ((name, value) in latestConfidences) {`,
  `                confidencesMap.putDouble(name, value)`,
  `            }`,
  `            map.putMap("confidences", confidencesMap)`,
  `            map.putString("topClass", latestTopClass)`,
  `            map.putDouble("topConfidence", latestTopConfidence)`,
  `            // Backward-compatible fields`,
  `            map.putDouble("snoreConfidence", latestConfidences["snoring"] ?: 0.0)`,
  `            map.putDouble("noiseConfidence", latestConfidences["noise"] ?: 0.0)`,
  `            map.putBoolean("isSnoring", latestIsSnoring)`,
  `            map.putDouble("amplitudeDb", latestAmplitudeDb)`,
  `        }`,
  `        promise.resolve(map)`,
  `    }`,
  ``,
  `    private fun releaseResources() {`,
  `        try { audioRecord?.stop() } catch (_: Exception) {}`,
  `        audioRecord?.release()`,
  `        audioRecord = null`,
  ``,
  `        wavOut?.let {`,
  `            try {`,
  `                it.flush()`,
  `                it.close()`,
  `                updateWavHeader(File(wavFilePath))`,
  `            } catch (_: Exception) {}`,
  `        }`,
  `        wavOut = null`,
  ``,
  `        interpreter?.close()`,
  `        interpreter = null`,
  `    }`,
  ``,
  `    private fun loadLabels(): List<String> {`,
  `        return try {`,
  `            reactApplicationContext.assets.open("labels.txt").bufferedReader().useLines { lines ->`,
  `                lines.map { it.trim() }.filter { it.isNotEmpty() }.toList()`,
  `            }`,
  `        } catch (e: Exception) {`,
  `            Log.w(TAG, "Failed to load labels.txt", e)`,
  `            emptyList()`,
  `        }`,
  `    }`,
  ``,
  `    private fun startAudioProcessing() {`,
  `        recordingThread = Thread {`,
  `            Process.setThreadPriority(Process.THREAD_PRIORITY_URGENT_AUDIO)`,
  `            val audioBuffer = mutableListOf<Short>()`,
  `            val readBuffer = ShortArray(640)`,
  ``,
  `            while (isRecording) {`,
  `                val read = audioRecord?.read(readBuffer, 0, readBuffer.size) ?: 0`,
  `                if (read > 0) {`,
  `                    // Write PCM samples to WAV file (little endian)`,
  `                    for (i in 0 until read) {`,
  `                        val s = readBuffer[i].toInt()`,
  `                        wavOut?.write(s and 0xFF)`,
  `                        wavOut?.write((s shr 8) and 0xFF)`,
  `                    }`,
  `                    wavDataBytes += read * 2`,
  ``,
  `                    // Accumulate for inference`,
  `                    for (i in 0 until read) audioBuffer.add(readBuffer[i])`,
  ``,
  `                    // Process every complete 1-second window`,
  `                    while (audioBuffer.size >= SAMPLES_PER_WINDOW) {`,
  `                        val window = ShortArray(SAMPLES_PER_WINDOW) { audioBuffer[it] }`,
  `                        audioBuffer.subList(0, SAMPLES_PER_WINDOW).clear()`,
  `                        processWindow(window)`,
  `                    }`,
  `                } else if (read < 0) {`,
  `                    Log.e(TAG, "AudioRecord read error: \$read")`,
  `                }`,
  `            }`,
  `        }.apply { start() }`,
  `    }`,
  ``,
  `    private fun processWindow(window: ShortArray) {`,
  `        val audio = DoubleArray(window.size) { window[it] / 32768.0 }`,
  `        val normalized = normalize(audio)`,
  `        val features = computeSpectrogramFeatures(normalized)`,
  ``,
  `        val rms = sqrt(audio.map { it * it }.average())`,
  `        val amplitudeDb = if (rms > 0.0) 20.0 * log10(rms) else -100.0`,
  ``,
  `        val inputBuf = ByteBuffer.allocateDirect(EXPECTED_FEATURES).order(ByteOrder.nativeOrder())`,
  `        for (f in features) {`,
  `            val q = ((f / INPUT_SCALE).roundToInt() + INPUT_ZERO_POINT).coerceIn(-128, 127)`,
  `            inputBuf.put(q.toByte())`,
  `        }`,
  `        inputBuf.rewind()`,
  ``,
  `        // Infer the number of output classes from the model itself rather than hard-coding 2.`,
  `        val outputShape = interpreter?.getOutputTensor(0)?.shape() ?: intArrayOf(labels.size)`,
  `        val classCount = outputShape.last().coerceAtLeast(1)`,
  `        val outputBuf = ByteBuffer.allocateDirect(classCount).order(ByteOrder.nativeOrder())`,
  `        interpreter?.run(inputBuf, outputBuf)`,
  `        outputBuf.rewind()`,
  ``,
  `        val logits = DoubleArray(classCount) { _ ->`,
  `            val q = outputBuf.get().toInt()`,
  `            (q - OUTPUT_ZERO_POINT) * OUTPUT_SCALE`,
  `        }`,
  `        val probs = softmax(logits)`,
  ``,
  `        // Build a name -> confidence map aligned with labels.txt. If the model has more classes`,
  `        // than labels, fall back to generic names so the JS side never receives an empty map.`,
  `        val confidences = mutableMapOf<String, Double>()`,
  `        for (i in probs.indices) {`,
  `            val name = labels.getOrElse(i) { "class_\$i" }`,
  `            confidences[name] = probs[i]`,
  `        }`,
  ``,
  `        val topIdx = probs.indices.maxByOrNull { probs[it] } ?: 0`,
  `        val topClass = labels.getOrElse(topIdx) { "class_\$topIdx" }`,
  `        val topConfidence = probs[topIdx]`,
  `        val snoringIndex = labels.indexOf("snoring")`,
  `        val isSnoring = if (snoringIndex >= 0) {`,
  `            probs[snoringIndex] > 0.5 && probs[snoringIndex] >= topConfidence`,
  `        } else {`,
  `            topClass == "snoring"`,
  `        }`,
  ``,
  `        synchronized(lock) {`,
  `            latestConfidences = confidences`,
  `            latestTopClass = topClass`,
  `            latestTopConfidence = topConfidence`,
  `            latestIsSnoring = isSnoring`,
  `            latestAmplitudeDb = amplitudeDb`,
  `        }`,
  `        Log.d(TAG, "Inference top=%s %.3f snoring=%.3f amp=%.1fdB".format(topClass, topConfidence, confidences["snoring"] ?: 0.0, amplitudeDb))`,
  `    }`,
  ``,
  `    private fun computeSpectrogramFeatures(audioWindow: DoubleArray): DoubleArray {`,
  `        val frameLength = (FRAME_LENGTH_MS * SAMPLE_RATE / 1000.0).roundToInt()`,
  `        val stride = (FRAME_STRIDE_MS * SAMPLE_RATE / 1000.0).roundToInt()`,
  `        val noiseFloorLinear = 10.0.pow(NOISE_FLOOR_DB / 10.0)`,
  `        val features = mutableListOf<Double>()`,
  ``,
  `        var start = 0`,
  `        while (start + frameLength <= audioWindow.size) {`,
  `            val frame = audioWindow.copyOfRange(start, start + frameLength)`,
  `            val windowed = applyHammingWindow(frame)`,
  `            val real = DoubleArray(FFT_LENGTH) { i -> if (i < windowed.size) windowed[i] else 0.0 }`,
  `            val imag = DoubleArray(FFT_LENGTH)`,
  `            fft(real, imag)`,
  ``,
  `            for (i in 0 until FFT_LENGTH / 2 + 1) {`,
  `                val magnitude = sqrt(real[i] * real[i] + imag[i] * imag[i])`,
  `                val power = magnitude * magnitude`,
  `                val clamped = max(power, noiseFloorLinear)`,
  `                features.add(10.0 * log10(clamped))`,
  `            }`,
  `            start += stride`,
  `        }`,
  ``,
  `        while (features.size < EXPECTED_FEATURES) features.add(0.0)`,
  `        return features.take(EXPECTED_FEATURES).toDoubleArray()`,
  `    }`,
  ``,
  `    private fun applyHammingWindow(frame: DoubleArray): DoubleArray {`,
  `        val n = frame.size`,
  `        return DoubleArray(n) { i ->`,
  `            val w = 0.54 - 0.46 * cos(2.0 * PI * i / (n - 1))`,
  `            frame[i] * w`,
  `        }`,
  `    }`,
  ``,
  `    private fun normalize(audio: DoubleArray): DoubleArray {`,
  `        val maxAbs = audio.maxOfOrNull { abs(it) } ?: 0.0`,
  `        if (maxAbs == 0.0) return audio`,
  `        return DoubleArray(audio.size) { audio[it] / maxAbs }`,
  `    }`,
  ``,
  `    private fun softmax(logits: DoubleArray): DoubleArray {`,
  `        val maxLogit = logits.maxOrNull() ?: 0.0`,
  `        val exps = DoubleArray(logits.size) { exp(logits[it] - maxLogit) }`,
  `        val sum = exps.sum()`,
  `        return DoubleArray(logits.size) { exps[it] / sum }`,
  `    }`,
  ``,
  `    // Iterative Cooley-Tukey FFT (power-of-two length only)`,
  `    private fun fft(real: DoubleArray, imag: DoubleArray) {`,
  `        val n = real.size`,
  `        var j = 0`,
  `        for (i in 1 until n) {`,
  `            var bit = n shr 1`,
  `            while (j >= bit) {`,
  `                j -= bit`,
  `                bit = bit shr 1`,
  `            }`,
  `            j += bit`,
  `            if (i < j) {`,
  `                val tempR = real[i]`,
  `                real[i] = real[j]`,
  `                real[j] = tempR`,
  `                val tempI = imag[i]`,
  `                imag[i] = imag[j]`,
  `                imag[j] = tempI`,
  `            }`,
  `        }`,
  ``,
  `        var len = 2`,
  `        while (len <= n) {`,
  `            val ang = 2.0 * PI / len`,
  `            val wlenR = cos(ang)`,
  `            val wlenI = -sin(ang)`,
  `            for (i in 0 until n step len) {`,
  `                var wR = 1.0`,
  `                var wI = 0.0`,
  `                for (k in 0 until len / 2) {`,
  `                    val uR = real[i + k]`,
  `                    val uI = imag[i + k]`,
  `                    val vR = real[i + k + len / 2] * wR - imag[i + k + len / 2] * wI`,
  `                    val vI = real[i + k + len / 2] * wI + imag[i + k + len / 2] * wR`,
  `                    real[i + k] = uR + vR`,
  `                    imag[i + k] = uI + vI`,
  `                    real[i + k + len / 2] = uR - vR`,
  `                    imag[i + k + len / 2] = uI - vI`,
  `                    val nextWR = wR * wlenR - wI * wlenI`,
  `                    val nextWI = wR * wlenI + wI * wlenR`,
  `                    wR = nextWR`,
  `                    wI = nextWI`,
  `                }`,
  `            }`,
  `            len = len shl 1`,
  `        }`,
  `    }`,
  ``,
  `    private fun writeWavHeader(out: DataOutputStream, dataSize: Int) {`,
  `        val totalSize = 36 + dataSize`,
  `        out.writeBytes("RIFF")`,
  `        writeIntLe(out, totalSize)`,
  `        out.writeBytes("WAVE")`,
  `        out.writeBytes("fmt ")`,
  `        writeIntLe(out, 16)`,
  `        writeShortLe(out, 1)`,
  `        writeShortLe(out, 1)`,
  `        writeIntLe(out, SAMPLE_RATE)`,
  `        writeIntLe(out, SAMPLE_RATE * 2)`,
  `        writeShortLe(out, 2)`,
  `        writeShortLe(out, 16)`,
  `        out.writeBytes("data")`,
  `        writeIntLe(out, dataSize)`,
  `    }`,
  ``,
  `    private fun updateWavHeader(file: File) {`,
  `        val dataSize = wavDataBytes`,
  `        val totalSize = 36 + dataSize`,
  `        RandomAccessFile(file, "rw").use { raf ->`,
  `            raf.seek(4)`,
  `            raf.writeIntLe(totalSize)`,
  `            raf.seek(40)`,
  `            raf.writeIntLe(dataSize)`,
  `        }`,
  `    }`,
  ``,
  `    private fun RandomAccessFile.writeIntLe(v: Int) {`,
  `        write(v and 0xFF)`,
  `        write((v shr 8) and 0xFF)`,
  `        write((v shr 16) and 0xFF)`,
  `        write((v shr 24) and 0xFF)`,
  `    }`,
  ``,
  `    private fun writeIntLe(out: DataOutputStream, v: Int) {`,
  `        write(v and 0xFF)`,
  `        write((v shr 8) and 0xFF)`,
  `        write((v shr 16) and 0xFF)`,
  `        write((v shr 24) and 0xFF)`,
  `    }`,
  ``,
  `    private fun writeShortLe(out: DataOutputStream, v: Int) {`,
  `        write(v and 0xFF)`,
  `        write((v shr 8) and 0xFF)`,
  `    }`,
  `}`,
  ``,
].join('\n');

const AUDIO_METER_PACKAGE_KT = [
  `package com.snoresleep.monitor`,
  ``,
  `import com.facebook.react.ReactPackage`,
  `import com.facebook.react.bridge.ReactApplicationContext`,
  `import com.facebook.react.bridge.NativeModule`,
  `import com.facebook.react.uimanager.ViewManager`,
  ``,
  `class AudioMeterPackage : ReactPackage {`,
  `    override fun createNativeModules(reactContext: ReactApplicationContext): List<NativeModule> {`,
  `        return listOf(AudioMeterModule(reactContext))`,
  `    }`,
  ``,
  `    override fun createViewManagers(reactContext: ReactApplicationContext): List<ViewManager<*, *>> {`,
  `        return emptyList()`,
  `    }`,
  `}`,
  ``,
].join('\n');

function withAudioMeter(config) {
  // 1. Write native module files and copy the TFLite model + labels into Android assets
  config = withDangerousMod(config, [
    'android',
    async (config) => {
      const root = config.modRequest.platformProjectRoot;
      const projectRoot = config.modRequest.projectRoot;
      const javaDir = path.join(root, 'app/src/main/java/com/snoresleep/monitor');
      fs.mkdirSync(javaDir, { recursive: true });
      fs.writeFileSync(path.join(javaDir, 'AudioMeterModule.kt'), AUDIO_METER_MODULE_KT);
      fs.writeFileSync(path.join(javaDir, 'AudioMeterPackage.kt'), AUDIO_METER_PACKAGE_KT);

      // Copy the quantized snore detection model and label file into Android assets.
      // labels.txt makes the native module generic: class names are no longer hard-coded.
      const assetsDir = path.join(root, 'app/src/main/assets');
      fs.mkdirSync(assetsDir, { recursive: true });

      const modelSrc = path.join(projectRoot, 'assets/snore_detection.tflite');
      const modelDst = path.join(assetsDir, 'snore_detection.tflite');
      if (fs.existsSync(modelSrc)) {
        fs.copyFileSync(modelSrc, modelDst);
      } else {
        throw new Error(`TFLite model not found at ${modelSrc}`);
      }

      const labelsSrc = path.join(projectRoot, 'assets/labels.txt');
      const labelsDst = path.join(assetsDir, 'labels.txt');
      if (fs.existsSync(labelsSrc)) {
        fs.copyFileSync(labelsSrc, labelsDst);
      } else {
        throw new Error(`labels.txt not found at ${labelsSrc}`);
      }

      return config;
    },
  ]);

  // 2. Add TensorFlow Lite dependency to app/build.gradle
  config = withDangerousMod(config, [
    'android',
    async (config) => {
      const root = config.modRequest.platformProjectRoot;
      const buildGradle = path.join(root, 'app/build.gradle');
      if (fs.existsSync(buildGradle)) {
        let contents = fs.readFileSync(buildGradle, 'utf8');
        const dep = 'implementation("org.tensorflow:tensorflow-lite:2.16.1")';
        if (!contents.includes('tensorflow-lite')) {
          contents = contents.replace(/dependencies\s*\{/, `dependencies {\n    ${dep}`);
          fs.writeFileSync(buildGradle, contents);
        }
      }
      return config;
    },
  ]);

  // 3. Modify MainApplication.kt to register AudioMeterPackage
  config = withMainApplication(config, (config) => {
    const contents = config.modResults.contents;

    if (contents.includes('AudioMeterPackage')) {
      return config;
    }

    if (/PackageList\(this\)\.packages\.apply\s*\{/.test(contents)) {
      config.modResults.contents = contents.replace(
        /PackageList\(this\)\.packages\.apply\s*\{/,
        'PackageList(this).packages.apply {\n              add(AudioMeterPackage())'
      );
      return config;
    }

    if (/val packages = PackageList\(this\)\.packages\.toMutableList\(\)/.test(contents)) {
      config.modResults.contents = contents.replace(
        /val packages = PackageList\(this\)\.packages\.toMutableList\(\)/,
        'val packages = PackageList(this).packages.toMutableList()\n            packages.add(AudioMeterPackage())'
      );
      return config;
    }

    if (/return PackageList\(this\)\.packages/.test(contents)) {
      config.modResults.contents = contents.replace(
        /return PackageList\(this\)\.packages/,
        'val packages = PackageList(this).packages.toMutableList()\n            packages.add(AudioMeterPackage())\n            return packages'
      );
      return config;
    }

    return config;
  });

  return config;
}

module.exports = withAudioMeter;
