// 由 App.tsx 抽离的样式表工厂：所有颜色均引用主题 token，以支持明/暗双主题。
// 由脚本从 App.tsx 的 StyleSheet.create 抽离后手工校订，勿在 App.tsx 内再维护样式。

import { Dimensions, StatusBar as RNStatusBar, StyleSheet } from 'react-native';
import type { Theme } from './theme';

const { width: SCREEN_W } = Dimensions.get('window');

export const makeStyles = (T: Theme) =>
  StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: T.background,
  },
  center: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: {
    marginTop: 16,
    color: T.textSecondary,
    fontSize: 15,
  },
  flex: {
    flex: 1,
  },
  homeContent: {
    padding: 16,
    paddingTop: 20,
  },
  heroCard: {
    backgroundColor: T.card,
    borderRadius: 28,
    padding: 22,
    overflow: 'hidden',
    shadowColor: T.shadow,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.07 * T.shadowOpacityScale,
    shadowRadius: 20,
    elevation: 5,
  },
  heroAccentBar: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 4,
    backgroundColor: T.primary,
  },
  heroHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 18,
  },
  appIconCircle: {
    width: 52,
    height: 52,
    borderRadius: 16,
    backgroundColor: T.primary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: T.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3 * T.shadowOpacityScale,
    shadowRadius: 8,
    elevation: 4,
  },
  title: {
    fontSize: 24,
    fontWeight: '800',
    color: T.text,
  },
  subtitle: {
    fontSize: 13,
    color: T.textTertiary,
    marginTop: 2,
  },
  warningBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: T.warningBg,
    borderRadius: 16,
    padding: 14,
    marginBottom: 14,
  },
  warningText: {
    color: T.warningFg,
    fontSize: 13,
    lineHeight: 18,
  },
  warningButton: {
    backgroundColor: T.warningFg,
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 14,
    marginLeft: 8,
  },
  warningButtonText: {
    color: T.onAccent,
    fontSize: 13,
    fontWeight: '700',
  },
  infoBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: T.infoBg,
    borderRadius: 16,
    padding: 14,
    marginBottom: 14,
  },
  infoText: {
    flex: 1,
    color: T.infoFg,
    fontSize: 13,
    lineHeight: 18,
    marginLeft: 12,
  },
  timerBox: {
    alignItems: 'center',
    marginVertical: 16,
  },
  timerPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: T.background,
    borderRadius: 20,
    paddingVertical: 6,
    paddingHorizontal: 14,
    marginBottom: 8,
  },
  timerDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 6,
  },
  timerLabel: {
    fontSize: 12,
    color: T.textSecondary,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  timerValue: {
    fontSize: 48,
    fontWeight: '200',
    color: T.text,
    fontVariant: ['tabular-nums'],
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  statCard: {
    width: '48.5%',
    backgroundColor: T.background,
    borderRadius: 18,
    paddingVertical: 14,
    paddingHorizontal: 12,
    alignItems: 'center',
    marginBottom: 12,
  },
  statIconCircle: {
    width: 40,
    height: 40,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  statValue: {
    fontSize: 22,
    fontWeight: '800',
    color: T.text,
    fontVariant: ['tabular-nums'],
    marginTop: 6,
  },
  statLabel: {
    fontSize: 12,
    color: T.textSecondary,
    marginTop: 2,
  },
  volumeBox: {
    backgroundColor: T.background,
    borderRadius: 18,
    padding: 16,
    marginBottom: 20,
  },
  volumeLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: T.text,
  },
  volumeBarBg: {
    height: 12,
    backgroundColor: T.border,
    borderRadius: 6,
    overflow: 'hidden',
  },
  volumeBarFill: {
    height: '100%',
    borderRadius: 6,
  },
  volumeDb: {
    fontSize: 12,
    color: T.textSecondary,
    marginTop: 6,
  },
  badge: {
    backgroundColor: `${T.primary}15`,
    borderRadius: 10,
    paddingVertical: 4,
    paddingHorizontal: 10,
  },
  badgeText: {
    fontSize: 12,
    fontWeight: '700',
    color: T.primary,
  },
  confidenceGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 14,
  },
  confidenceChip: {
    flex: 1,
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: 'center',
    marginHorizontal: 3,
  },
  confidenceLabel: {
    fontSize: 11,
    fontWeight: '700',
  },
  confidenceValue: {
    fontSize: 16,
    fontWeight: '800',
    marginTop: 2,
    fontVariant: ['tabular-nums'],
  },
  topClassRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
    backgroundColor: T.card,
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  topClassText: {
    fontSize: 12,
    color: T.textSecondary,
    marginLeft: 6,
    fontWeight: '600',
  },
  intensityText: {
    fontSize: 12,
    fontWeight: '700',
    marginLeft: 4,
  },
  maxVolumeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
  },
  durationRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 10,
    gap: 8,
  },
  durationItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  durationDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginRight: 4,
  },
  durationLabel: {
    fontSize: 11,
    color: T.textSecondary,
  },
  intensityBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderRadius: 8,
    paddingVertical: 4,
    paddingHorizontal: 10,
    marginTop: 8,
  },
  mainButton: {
    borderRadius: 20,
    paddingVertical: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: T.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12 * T.shadowOpacityScale,
    shadowRadius: 10,
    elevation: 4,
  },
  startButton: {
    backgroundColor: T.primary,
  },
  stopButton: {
    backgroundColor: T.danger,
  },
  mainButtonText: {
    color: T.onAccent,
    fontSize: 17,
    fontWeight: '700',
  },
  tipRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
  },
  tipText: {
    fontSize: 12,
    color: T.textTertiary,
    marginLeft: 6,
  },
  navRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 16,
  },
  navButton: {
    backgroundColor: T.card,
    borderRadius: 20,
    paddingVertical: 16,
    flex: 1,
    marginHorizontal: 6,
    alignItems: 'center',
    shadowColor: T.shadow,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06 * T.shadowOpacityScale,
    shadowRadius: 10,
    elevation: 2,
  },
  navIconCircle: {
    width: 44,
    height: 44,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  navButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: T.text,
    marginTop: 6,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: (RNStatusBar.currentHeight || 0) + 12,
    paddingBottom: 12,
    backgroundColor: T.card,
    borderBottomWidth: 1,
    borderBottomColor: T.border,
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: T.text,
  },
  emptyBox: {
    alignItems: 'center',
    marginTop: 80,
  },
  emptyText: {
    color: T.textSecondary,
    fontSize: 17,
    fontWeight: '700',
    marginTop: 16,
  },
  emptySubText: {
    color: T.textTertiary,
    fontSize: 13,
    marginTop: 6,
  },
  historyItem: {
    backgroundColor: T.card,
    borderRadius: 20,
    padding: 16,
    marginBottom: 12,
    shadowColor: T.shadow,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05 * T.shadowOpacityScale,
    shadowRadius: 10,
    elevation: 2,
  },
  historyRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  historyTime: {
    fontSize: 16,
    fontWeight: '700',
    color: T.text,
  },
  historyMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
  },
  historyMeta: {
    fontSize: 13,
    color: T.textSecondary,
    marginLeft: 4,
  },
  historyCountRow: {
    flexDirection: 'row',
    marginTop: 10,
  },
  historyCount: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: T.background,
    borderRadius: 10,
    paddingVertical: 4,
    paddingHorizontal: 8,
    marginRight: 8,
  },
  historyCountText: {
    fontSize: 12,
    fontWeight: '700',
    color: T.text,
    marginLeft: 4,
  },
  qualityBadge: {
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  qualityText: {
    color: T.onAccent,
    fontWeight: '800',
    fontSize: 13,
  },
  apneaRiskBadge: {
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  apneaRiskText: {
    color: T.onAccent,
    fontWeight: '800',
    fontSize: 13,
  },
  card: {
    backgroundColor: T.card,
    borderRadius: 24,
    padding: 20,
    shadowColor: T.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05 * T.shadowOpacityScale,
    shadowRadius: 8,
    elevation: 2,
  },
  detailTime: {
    fontSize: 18,
    fontWeight: '800',
    color: T.text,
  },
  detailStatsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  detailStatCard: {
    width: (SCREEN_W - 72) / 3,
    backgroundColor: T.background,
    borderRadius: 16,
    paddingVertical: 12,
    alignItems: 'center',
    marginBottom: 10,
  },
  detailStat: {
    alignItems: 'center',
  },
  detailStatValue: {
    fontSize: 16,
    fontWeight: '800',
    color: T.text,
    fontVariant: ['tabular-nums'],
    marginTop: 6,
  },
  detailStatLabel: {
    fontSize: 11,
    color: T.textSecondary,
    marginTop: 2,
  },
  qualityBadgeLarge: {
    borderRadius: 18,
    paddingVertical: 14,
    alignItems: 'center',
    marginBottom: 14,
  },
  qualityTextLarge: {
    color: T.onAccent,
    fontSize: 15,
    fontWeight: '800',
  },
  intensityRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  intensityBlock: {
    flex: 1,
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: 'center',
    marginHorizontal: 4,
  },
  recordingBox: {
    marginBottom: 24,
  },
  emptyRecordingBox: {
    alignItems: 'center',
    backgroundColor: T.background,
    borderRadius: 16,
    paddingVertical: 24,
    marginBottom: 24,
  },
  emptyEventBox: {
    alignItems: 'center',
    backgroundColor: T.successTint,
    borderRadius: 16,
    paddingVertical: 24,
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: T.text,
    marginBottom: 12,
  },
  noRecordingText: {
    color: T.textSecondary,
    fontSize: 13,
    marginTop: 8,
  },
  disclaimerText: {
    color: T.textTertiary,
    fontSize: 12,
    lineHeight: 17,
    marginBottom: 14,
  },
  eventRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 10,
    backgroundColor: T.card,
    borderRadius: 14,
    marginBottom: 10,
    borderLeftWidth: 4,
    shadowColor: T.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04 * T.shadowOpacityScale,
    shadowRadius: 6,
    elevation: 1,
  },
  eventIconCircle: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  eventIndex: {
    color: T.primary,
    fontWeight: '700',
    fontSize: 13,
  },
  eventClock: {
    color: T.textSecondary,
    fontSize: 12,
    marginTop: 2,
    fontVariant: ['tabular-nums'],
  },
  settingsDesc: {
    fontSize: 13,
    color: T.textSecondary,
    lineHeight: 19,
    marginBottom: 12,
  },
  settingSection: {
    marginBottom: 8,
  },
  settingHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  settingIconCircle: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  thresholdValue: {
    fontSize: 36,
    fontWeight: '800',
    color: T.text,
    textAlign: 'center',
    marginBottom: 12,
  },
  sliderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  adjustButton: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: T.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  adjustButtonText: {
    color: T.onAccent,
    fontSize: 22,
    fontWeight: '700',
    lineHeight: 26,
  },
  thresholdTrack: {
    flex: 1,
    height: 8,
    backgroundColor: T.border,
    borderRadius: 4,
    marginHorizontal: 14,
    overflow: 'hidden',
  },
  thresholdFill: {
    height: '100%',
    borderRadius: 4,
  },
  divider: {
    height: 1,
    backgroundColor: T.border,
    marginVertical: 18,
  },
  // —— 首页「高级信息」折叠 ——
  advancedToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: 10,
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: T.border,
  },
  advancedToggleText: {
    fontSize: 12,
    fontWeight: '700',
    color: T.textSecondary,
    marginRight: 4,
  },
  // —— 设置页「外观主题」分段选择 ——
  segmentRow: {
    flexDirection: 'row',
    backgroundColor: T.border,
    borderRadius: 12,
    padding: 4,
  },
  segmentItem: {
    flex: 1,
    paddingVertical: 9,
    borderRadius: 9,
    alignItems: 'center',
  },
  segmentItemActive: {
    backgroundColor: T.card,
    shadowColor: T.shadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08 * T.shadowOpacityScale,
    shadowRadius: 3,
    elevation: 1,
  },
  segmentText: {
    fontSize: 13,
    fontWeight: '600',
    color: T.textSecondary,
  },
  segmentTextActive: {
    color: T.primary,
    fontWeight: '800',
  },
  // —— 首次启动隐私同意页 ——
  consentBullet: {
    fontSize: 13,
    lineHeight: 21,
    color: T.textSecondary,
    marginBottom: 8,
  },
  consentLink: {
    fontSize: 13,
    fontWeight: '600',
    color: T.primary,
    textAlign: 'center',
    marginTop: 12,
    paddingVertical: 8,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  updateModal: {
    width: '100%',
    maxWidth: 320,
    backgroundColor: T.card,
    borderRadius: 24,
    padding: 26,
    alignItems: 'center',
    shadowColor: T.shadow,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.25 * T.shadowOpacityScale,
    shadowRadius: 20,
    elevation: 10,
  },
  updateIconCircle: {
    width: 64,
    height: 64,
    borderRadius: 22,
    backgroundColor: `${T.primary}15`,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  updateModalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: T.text,
    marginBottom: 6,
  },
  updateModalStatus: {
    fontSize: 13,
    color: T.textSecondary,
    marginBottom: 18,
  },
  progressTrack: {
    width: '100%',
    height: 10,
    backgroundColor: T.border,
    borderRadius: 5,
    overflow: 'hidden',
    marginBottom: 12,
  },
  progressFill: {
    height: '100%',
    backgroundColor: T.primary,
    borderRadius: 5,
  },
  updateModalPercent: {
    fontSize: 16,
    fontWeight: '800',
    color: T.primary,
  },
  heroTitleBlock: {
    flex: 1,
    marginLeft: 14,
  },
  updateBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: T.danger,
    borderRadius: 12,
    paddingVertical: 6,
    paddingHorizontal: 10,
    shadowColor: T.danger,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25 * T.shadowOpacityScale,
    shadowRadius: 4,
    elevation: 3,
  },
  updateBadgeText: {
    color: T.onAccent,
    fontSize: 12,
    fontWeight: '800',
    marginLeft: 4,
  },
  volumeHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  volumeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  volumeState: {
    fontSize: 12,
    marginTop: 6,
    fontWeight: '700',
  },
  emptyIconCircle: {
    width: 96,
    height: 96,
    borderRadius: 32,
    backgroundColor: `${T.primary}12`,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  detailHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 18,
  },
  detailIconCircle: {
    width: 52,
    height: 52,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  detailSubTime: {
    fontSize: 13,
    color: T.textSecondary,
    marginTop: 2,
  },
  timeline: {
    marginTop: 4,
  },
  eventBody: {
    flex: 1,
    marginLeft: 12,
  },
  versionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    marginBottom: 12,
  },
  newVersionBadge: {
    backgroundColor: `${T.danger}15`,
    borderRadius: 10,
    paddingVertical: 4,
    paddingHorizontal: 10,
  },
  newVersionBadgeText: {
    color: T.danger,
    fontSize: 12,
    fontWeight: '700',
  },
  });
